# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6418ad7df29e71c3f8ad3642c9e853a3684ea21c15e58bb63b327ae6572e1cb176331e6f3cb7b186b9f754069f3225938a4c0131b3ce1875cc7c88acc9ffcafd

test:
  secret_key_base: 3941e1907ddec3a5ebdb887fc0171e2ab051d660c638f6ba730a31b335f8d317c84764289ff51738e7a2a246d97a61869be77cd7ee633bec469a756cdab1f0d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
